// GENERATED BY scripts/generate_icon_file
import "package:vector_graphics/vector_graphics.dart";

const comment = AssetBytesLoader("assets/icons/compiled/comment.svg.vec");
const exploreFilled = AssetBytesLoader("assets/icons/compiled/explore-filled.svg.vec");
const exploreOutlined = AssetBytesLoader("assets/icons/compiled/explore-outlined.svg.vec");
const heartFilled = AssetBytesLoader("assets/icons/compiled/heart-filled.svg.vec");
const heartOutlined = AssetBytesLoader("assets/icons/compiled/heart-outlined.svg.vec");
const homeFilled = AssetBytesLoader("assets/icons/compiled/home-filled.svg.vec");
const homeOutlined = AssetBytesLoader("assets/icons/compiled/home-outlined.svg.vec");
const quote = AssetBytesLoader("assets/icons/compiled/quote.svg.vec");
const retweet = AssetBytesLoader("assets/icons/compiled/retweet.svg.vec");
